(function(){'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function n(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
n("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.H=b.prototype}var ma="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};
n("Object.assign",function(a){return a||ma});n("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});n("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});n("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
n("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});n("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var t=this||self;var na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var oa,u;a:{for(var pa=["CLOSURE_FLAGS"],v=t,qa=0;qa<pa.length;qa++)if(v=v[pa[qa]],null==v){u=null;break a}u=v}var ra=u&&u[610401301];oa=null!=ra?ra:!1;var x,sa=t.navigator;x=sa?sa.userAgentData||null:null;function ta(a){return oa?x?x.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function z(a){var b;a:{if(b=t.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function A(){return oa?!!x&&0<x.brands.length:!1}function ua(){return A()?ta("Chromium"):(z("Chrome")||z("CriOS"))&&!(A()?0:z("Edge"))||z("Silk")};var va=A()?!1:z("Trident")||z("MSIE");function wa(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function xa(a){a=void 0===a?document:a;return a.createElement("img")};function ya(a,b,c){var d=!1;d=void 0===d?!1:d;a.google_image_requests||(a.google_image_requests=[]);var e=xa(a.document);if(c){var f=function(){if(c){var h=a.google_image_requests,g=na(h,e);0<=g&&Array.prototype.splice.call(h,g,1)}e.removeEventListener&&e.removeEventListener("load",f,!1);e.removeEventListener&&e.removeEventListener("error",f,!1)};e.addEventListener&&e.addEventListener("load",f,!1);e.addEventListener&&e.addEventListener("error",f,!1)}d&&(e.attributionSrc="");e.src=b;a.google_image_requests.push(e)}
;function za(a){t.setTimeout(function(){throw a;},0)};!z("Android")||ua();ua();z("Safari")&&(ua()||(A()?0:z("Coast"))||(A()?0:z("Opera"))||(A()?0:z("Edge"))||(A()?ta("Microsoft Edge"):z("Edg/"))||A()&&ta("Opera"));var Aa={},B=null;
function Ba(a){var b;void 0===b&&(b=0);if(!B){B={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Aa[e]=f;for(var h=0;h<f.length;h++){var g=f[h];void 0===B[g]&&(B[g]=h)}}}b=Aa[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var k=a[f],l=a[f+1];g=a[f+2];h=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[e++]=h+k+l+g}h=0;g=d;switch(a.length-f){case 2:h=
a[f+1],g=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+g+d}return c.join("")};var Ca,Da="undefined"!==typeof TextEncoder;var Ea="undefined"!==typeof Uint8Array,Fa=!va&&"function"===typeof btoa;var Ga=0,Ha=0,Ia;function Ja(){this.g=[]}Ja.prototype.length=function(){return this.g.length};Ja.prototype.end=function(){var a=this.g;this.g=[];return a};function C(a,b){for(;127<b;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function Ka(a,b){if(0<=b)C(a,b);else{for(var c=0;9>c;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function La(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function Ma(){this.l=[];this.i=0;this.g=new Ja}function D(a,b){0!==b.length&&(a.l.push(b),a.i+=b.length)};function E(a){this.g=a};function F(a){return Array.prototype.slice.call(a)};var G="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0,H=G?function(a,b){a[G]|=b}:function(a,b){void 0!==a.j?a.j|=b:Object.defineProperties(a,{j:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Na(a){var b=I(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=F(a)),J(a,b|1))}
var Oa=G?function(a,b){a[G]&=~b}:function(a,b){void 0!==a.j&&(a.j&=~b)},I=G?function(a){return a[G]|0}:function(a){return a.j|0},L=G?function(a){return a[G]}:function(a){return a.j},J=G?function(a,b){a[G]=b}:function(a,b){void 0!==a.j?a.j=b:Object.defineProperties(a,{j:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Pa(a,b){Object.isFrozen(a)&&(a=F(a));J(a,b);return a}function Qa(a){H(a,1);return a}function Ra(a,b){J(b,(a|0)&-255)}function Sa(a,b){J(b,(a|34)&-221)}
function M(a){a=a>>11&1023;return 0===a?536870912:a};var N={};function O(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var P,Ta=[];J(Ta,39);P=Object.freeze(Ta);function Q(a){if(a&2)throw Error();};function Ua(){var a=Error();wa(a,"incident");return a};function Va(a){if(!Number.isFinite(a)){var b=Ua();za(b)}return a}function Wa(a){if("number"!==typeof a)throw a=Error(),wa(a,"warning"),a;if(!Number.isFinite(a)){var b=Ua();za(b)}return a}function Xa(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return a}function Ya(a){if(null!=a&&"string"!==typeof a)throw Error();return a};var Za,$a,ab;function bb(a){switch(typeof a){case "boolean":return $a||($a=[0,void 0,!0]);case "number":return 0<a?void 0:0===a?ab||(ab=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}
function R(a,b,c){null==a&&(a=Za);Za=void 0;if(null==a){var d=96;c?(a=[c],d|=512):a=[];b&&(d=d&-2095105|(b&1023)<<11)}else{if(!Array.isArray(a))throw Error();d=I(a);if(d&64)return a;d|=64;if(c&&(d|=512,c!==a[0]))throw Error();a:{c=a;var e=c.length;if(e){var f=e-1,h=c[f];if(O(h)){d|=256;b=+!!(d&512)-1;e=f-b;1024<=e&&(cb(c,b,h),e=1023);d=d&-2095105|(e&1023)<<11;break a}}b&&(h=+!!(d&512)-1,b=Math.max(b,e-h),1024<b&&(cb(c,h,{}),d|=256,b=1023),d=d&-2095105|(b&1023)<<11)}}J(a,d);return a}
function cb(a,b,c){for(var d=1023+b,e=a.length,f=d;f<e;f++){var h=a[f];null!=h&&h!==c&&(c[f-b]=h)}a.length=d+1;a[d]=c};function db(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&Ea&&null!=a&&a instanceof Uint8Array){if(Fa){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else a=Ba(a);return a}}return a};function eb(a,b,c){a=F(a);var d=a.length,e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var f in e)b[f]=c(e[f])}return a}function fb(a,b,c,d,e,f){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&I(a)&1?void 0:f&&I(a)&2?a:hb(a,b,c,void 0!==d,e,f);else if(O(a)){var h={},g;for(g in a)h[g]=fb(a[g],b,c,d,e,f);a=h}else a=b(a,d);return a}}
function hb(a,b,c,d,e,f){var h=d||c?I(a):0;d=d?!!(h&32):void 0;a=F(a);for(var g=0;g<a.length;g++)a[g]=fb(a[g],b,c,d,e,f);c&&c(h,a);return a}function ib(a){return a.m===N?a.toJSON():db(a)};function jb(a,b,c){c=void 0===c?Sa:c;if(null!=a){if(Ea&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=I(a);return d&2?a:!b||d&68||!(d&32||0===d)?hb(a,jb,d&4?Sa:c,!0,!1,!0):(J(a,d|34),a)}a.m===N&&(b=a.h,c=L(b),a=c&2?a:kb(a,b,c,!0));return a}}function kb(a,b,c,d){a=a.constructor;Za=b=lb(b,c,d);b=new a(b);Za=void 0;return b}function lb(a,b,c){var d=c||b&2?Sa:Ra,e=!!(b&32);a=eb(a,b,function(f){return jb(f,e,d)});H(a,32|(c?2:0));return a};function mb(a,b,c,d){if(-1===c)return null;if(c>=M(b)){if(b&256)return a[a.length-1][c]}else{var e=a.length;if(d&&b&256&&(d=a[e-1][c],null!=d))return d;b=c+(+!!(b&512)-1);if(b<e)return a[b]}}function nb(a,b,c){a=a.h;var d=L(a);Q(d);S(a,d,b,c)}function S(a,b,c,d,e){var f=M(b);if(c>=f||e){e=b;if(b&256)f=a[a.length-1];else{if(null==d)return;f=a[f+(+!!(b&512)-1)]={};e|=256}f[c]=d;e!==b&&J(a,e)}else a[c+(+!!(b&512)-1)]=d,b&256&&(a=a[a.length-1],c in a&&delete a[c])}
function T(a,b,c,d){a=a.h;var e=L(a);Q(e);for(var f=0,h=0;h<c.length;h++){var g=c[h];null!=mb(a,e,g)&&(0!==f&&S(a,e,f),f=g)}(c=f)&&c!==b&&null!=d&&S(a,e,c);S(a,e,b,d)}
function ob(a,b,c,d,e,f){var h=!!(b&2);var g=b&2;var k=mb(a,b,d,e);Array.isArray(k)||(k=P);var l=I(k);l&1||Qa(k);g?l&2||H(k,34):l&32&&!(l&2)&&Oa(k,32);g=k;if(g===P||!(I(g)&4)){l=g;g=!!(b&2);k=!!(I(l)&2);h=l;!g&&k&&(l=F(l));var m=b|(k?2:0);k=k||void 0;for(var p=0,w=0;p<l.length;p++){var q=l[p];var gb=c,K=!1;if(null==q||"object"!==typeof q||(K=Array.isArray(q))||q.m!==N)if(K){var y=K=I(q);0===y&&(y|=m&32);y|=m&2;y!==K&&J(q,y);q=new gb(q)}else q=void 0;void 0!==q&&(k=k||L(q.h)&2,l[w++]=q)}w<p&&(l.length=
w);c=l;l=I(c);m=l|5;k=k?m&-9:m|8;l!=k&&(c=Pa(c,k));l=c;h!==l&&S(a,b,d,l,e);(g&&2!==f||1===f)&&Object.freeze(l);return l}if(3===f)return g;h?2===f&&(f=I(g),g=F(g),J(g,f),S(a,b,d,g,e)):(c=Object.isFrozen(g),1===f?c||Object.freeze(g):(f=I(g),h=f&-35,c&&(g=F(g),f=0,S(a,b,d,g,e)),f!==h&&J(g,h)));return g}function pb(a,b){var c=a.h,d=L(c);a=!!(d&2);b=ob(c,d,qb,b,void 0,a?1:2);if(!(a||I(b)&8)){for(a=0;a<b.length;a++){c=b[a];d=c.h;var e=L(d);d=e&2?kb(c,d,e,!1):c;c!==d&&(b[a]=d)}H(b,8)}return b}
function rb(a,b,c){var d=a.h,e=L(d);Q(e);if(null!=c){for(var f=!!c.length,h=0;h<c.length;h++){var g=c[h];f=f&&!(I(g.h)&2)}h=I(c);g=h|1;g=(f?g|8:g&-9)|4;g!=h&&(c=Pa(c,g))}null==c&&(c=void 0);S(d,e,b,c);return a};function U(a,b,c){this.h=R(a,b,c)}U.prototype.toJSON=function(){var a=hb(this.h,ib,void 0,void 0,!1,!1);return sb(this,a,!0)};U.prototype.m=N;U.prototype.toString=function(){return sb(this,this.h,!1).toString()};
function sb(a,b,c){var d=a.constructor.v,e=M(L(c?a.h:b)),f=!1;if(d){if(!c){b=F(b);var h;if(b.length&&O(h=b[b.length-1]))for(f=0;f<d.length;f++)if(d[f]>=e){Object.assign(b[b.length-1]={},h);break}f=!0}e=b;c=!c;h=L(a.h);a=M(h);h=+!!(h&512)-1;for(var g,k,l=0;l<d.length;l++)if(k=d[l],k<a){k+=h;var m=e[k];null==m?e[k]=c?P:Qa([]):c&&m!==P&&Na(m)}else g||(m=void 0,e.length&&O(m=e[e.length-1])?g=m:e.push(g={})),m=g[k],null==g[k]?g[k]=c?P:Qa([]):c&&m!==P&&Na(m)}d=b.length;if(!d)return b;var p;if(O(g=b[d-1])){a:{var w=
g;e={};c=!1;for(var q in w)a=w[q],Array.isArray(a)&&a!=a&&(c=!0),null!=a?e[q]=a:c=!0;if(c){for(var gb in e){w=e;break a}w=null}}w!=g&&(p=!0);d--}for(;0<d;d--){g=b[d-1];if(null!=g)break;var K=!0}if(!p&&!K)return b;var y;f?y=b:y=Array.prototype.slice.call(b,0,d);b=y;f&&(b.length=d);w&&b.push(w);return b};var tb=Symbol();function ub(a){var b=a[tb];if(!b){var c=vb(a);b=function(d,e){return wb(d,e,c)};a[tb]=b}return b}var xb=Symbol();function yb(a,b){return b.g}function zb(a,b,c){var d,e,f=b.g;return function(h,g,k){return f(h,g,k,e||(e=vb(c).i),d||(d=ub(c)))}}
function vb(a){var b=a[xb];if(b)return b;a:{b=a[xb]={};var c=yb,d=zb;b.i=bb(a[0]);var e=1;if(a.length>e&&!(a[e]instanceof E)){var f=a[e++];if(Array.isArray(f)){b.l=f[0];b.g=f[1];break a}b.g=f}for(f=0;e<a.length;){var h=a[e++],g=a[e];"number"===typeof g?(e++,f+=g):f++;for(g=e;g<a.length&&!(a[g]instanceof E);)g++;if(g-=e){var k=a,l=e,m=k[l];"function"==typeof m&&(m=m(),k[l]=m);if((k=Array.isArray(m))&&!(k=Ab in m||xb in m)&&(k=0<m.length)){k=m;l=k[0];var p=bb(l);null!=p&&p!==l&&(k[0]=p);k=null!=p}(m=
k?m:void 0)?(e++,1===g?(h=d(f,h,m,void 0,void 0),void 0!==h&&(b[f]=h)):(h=d(f,h,m,a[e++],void 0),void 0!==h&&(b[f]=h))):(h=c(f,h,a[e++],void 0),void 0!==h&&(b[f]=h))}else h=c(f,h,void 0,void 0),void 0!==h&&(b[f]=h)}}Ab in a&&xb in a&&(a.length=0);return b}var Ab=Symbol();function Bb(a,b){var c=a[b];if(c)return c;if(c=a.g)if(c=c[b]){var d=c.F,e=c.G.g;if(d){var f=ub(d),h=vb(d).i;c=function(g,k,l){return e(g,k,l,h,f)}}else c=e;return a[b]=c}}
function wb(a,b,c){for(var d=L(a),e=+!!(d&512)-1,f=a.length,h=f+(d&256?-1:0),g=d&512?1:0;g<h;g++){var k=a[g];if(null!=k){var l=g-e,m=Bb(c,l);m&&m(b,k,l)}}if(d&256){a=a[f-1];for(var p in a)d=+p,Number.isNaN(d)||(e=a[p],null!=e&&(f=Bb(c,d))&&f(b,e,d))}}
function Cb(a,b,c){b=null==b||"string"===typeof b?b:void 0;if(null!=b){var d=!1;d=void 0===d?!1:d;if(Da){if(d&&/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b))throw Error("Found an unpaired surrogate");b=(Ca||(Ca=new TextEncoder)).encode(b)}else{for(var e=0,f=new Uint8Array(3*b.length),h=0;h<b.length;h++){var g=b.charCodeAt(h);if(128>g)f[e++]=g;else{if(2048>g)f[e++]=g>>6|192;else{if(55296<=g&&57343>=g){if(56319>=g&&h<b.length){var k=b.charCodeAt(++h);if(56320<=k&&
57343>=k){g=1024*(g-55296)+k-56320+65536;f[e++]=g>>18|240;f[e++]=g>>12&63|128;f[e++]=g>>6&63|128;f[e++]=g&63|128;continue}else h--}if(d)throw Error("Found an unpaired surrogate");g=65533}f[e++]=g>>12|224;f[e++]=g>>6&63|128}f[e++]=g&63|128}}b=e===f.length?f:f.subarray(0,e)}C(a.g,8*c+2);C(a.g,b.length);D(a,a.g.end());D(a,b)}}
var Db=new E(function(a,b,c){b=null==b?b:"number"===typeof b||"NaN"===b||"Infinity"===b||"-Infinity"===b?Number(b):void 0;null!=b&&(C(a.g,8*c+1),a=a.g,c=Ia||(Ia=new DataView(new ArrayBuffer(8))),c.setFloat64(0,+b,!0),Ga=c.getUint32(0,!0),Ha=c.getUint32(4,!0),La(a,Ga),La(a,Ha))}),Eb=new E(function(a,b,c){b=Xa(b);null!=b&&null!=b&&(C(a.g,8*c),Ka(a.g,b))}),Fb=new E(Cb),Gb=new E(Cb),Hb;
Hb=new E(function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++){var h=a,g=b[f],k=c,l=e;g=g instanceof U?g.h:Array.isArray(g)?R(g,d[0],d[1]):void 0;if(null!=g){var m=h;C(m.g,8*k+2);k=m.g.end();D(m,k);k.push(m.i);l(g,h);l=k;g=l.pop();for(g=h.i+h.g.length()-g;127<g;)l.push(g&127|128),g>>>=7,h.i++;l.push(g);h.i++}}});var Ib=new E(function(a,b,c){b=Xa(b);null!=b&&(b=parseInt(b,10),C(a.g,8*c),Ka(a.g,b))});function qb(a){this.h=R(a)}la(qb,U);var V=[1,2,3],Jb=[4,5],Kb=[0,Ib,V,Ib,V,Gb,V,Db,Jb,Gb,Jb,Eb];function Lb(a){this.h=R(a)}la(Lb,U);Lb.v=[1];Lb.prototype.g=function(a){return function(){var b=new Ma;wb(this.h,b,vb(a));D(b,b.g.end());for(var c=new Uint8Array(b.i),d=b.l,e=d.length,f=0,h=0;h<e;h++){var g=d[h];c.set(g,f);f+=g.length}b.l=[c];return c}}([0,Hb,Kb,Fb,Eb,Fb,Eb]);function Mb(a){this.h=R(a)}la(Mb,U);Mb.prototype.setData=function(a,b){var c=qb,d=this.h,e=L(d);Q(e);d=ob(d,e,c,2,!1,2);b=null!=b?b:new c;if("number"!==typeof a||0>a||a>d.length)throw Error();void 0!=a?d.splice(a,1,b):d.push(b);I(b.h)&2&&Oa(d,8);return this};Mb.v=[1,2];function Nb(a){this.i=a;this.data=[];this.g=[]}Nb.prototype.setData=function(a,b,c){this.i.includes(c)&&this.data.push({key:a,value:b,channel:c})};function Ob(a){return a.data.some(function(b){return 1===b.channel})}Nb.prototype.setAttribute=function(a,b){this.g.push({key:a,value:b})};
function Pb(a,b,c,d){var e=new qb;"string"===typeof a?T(e,3,V,Ya(a)):d?T(e,1,V,null==a?a:Va(a)):T(e,2,V,null==a?a:Va(a));if("number"===typeof b){if(null==b)a=b;else{if("number"!==typeof b)throw Error("Value of float/double field must be a number, found "+typeof b+": "+b);a=b}T(e,4,Jb,a)}else T(e,5,Jb,Ya(b));c&&nb(e,6,null==c?c:Wa(c));return e};function W(){this.g=new Nb([]);this.B=Date.now();this.i=[];this.u=this.o=!1;this.s=100}
W.prototype.init=function(a,b,c,d,e,f){var h=this;this.g=new Nb(b);this.D=a;this.A=e;this.C=c;if(d){b=a=NaN;d=r(d);for(c=d.next();!c.done;c=d.next())e=r(c.value),c=e.next().value,e=e.next().value,6===c?a=Number(e):5===c?b=Number(e):this.g.setAttribute(c,e);!isNaN(a)&&0<=a?this.s=a:isNaN(b)||(this.o=!0,setInterval(this.l.bind(this),b),setTimeout(function(){Qb(h,"timeout")},3E5),document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&Qb(h,"document_hidden")}),window.addEventListener("beforeunload",
function(){Qb(h,"beforeunload")}))}if(f){f=r(f);for(a=f.next();!a.done;a=f.next())d=r(a.value),a=d.next().value,b=d.next().value,d=d.next().value,this.setData(a,b,d);"complete"===document.readyState?this.send():window.addEventListener("load",function(){h.send()})}};W.prototype.getBaseTime=function(){return this.B};W.prototype.setData=function(a,b,c){this.g.setData(a,b,c);this.i[c]?this.i[c]++:this.i[c]=1};W.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};
W.prototype.send=function(a){var b=this;if(!this.o){var c=Ob(this.g)?0:this.s;a=null!=a?a:c;0<a?setTimeout(function(){return void b.l()},a):this.l()}};
W.prototype.l=function(){if(0<this.g.data.length){var a=this.D,b=this.A,c=this.C,d=this.g,e=[];var f=r(d.g);for(var h=f.next();!h.done;h=f.next())h=h.value,e.push(Pb(h.key,h.value,void 0,!0));f=[];d=r(d.data);for(h=d.next();!h.done;h=d.next())h=h.value,f.push(Pb(h.key,h.value,h.channel,!1));d=new Mb;e=rb(d,1,e);f=rb(e,2,f);e=new Lb;f=pb(f,1).concat(pb(f,2));e=rb(e,1,f);a&&nb(e,2,Ya(a));c&&nb(e,4,Ya(c));b&&nb(e,5,null==b?b:Wa(b));a="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+Ba(e.g()).replace(/\//g,
"_").replace(/\+/g,"-");b=window;var g=void 0===g?!1:g;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&b.navigator.sendBeacon?b.navigator.sendBeacon(a):ya(b,a,void 0===g?!1:g);this.g.data=[]}};function Qb(a,b){a.u||(a.g.setData(32,b,4),a.i.forEach(function(c,d){a.g.setData(31,c,d)}),a.l(),a.u=!0)}
if(!window.mys||!window.mys.pingback){var Rb=new W,X=["mys","pingback"],Y=t;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Rb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Rb};}).call(this);
